name: Kevin Yank
markdown: kramdown
highlighter: pygments
description: Kevin Yank’s website
url: http://kevinyank.com
permalink: /posts/:title
paginate: 5
paginate_path: /blog/page/:num
lang: en-AU
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - Gemfile
  - Gemfile.lock
